### ISSUE TITLE
not working with pychromecast >= 0.6

### ISSUE THREAD

**Issue by kristianperkins** [jaapz/cast#3]
When running cast with newer versions of pychromecast (`0.6` and up) `cast` commands fail with errors like:

```
$ cast status                  
Traceback (most recent call last):
  File "/home/kperkins/.virtualenvs/cast/bin/cast", line 9, in <module>
    load_entry_point('cast==0.1.1', 'console_scripts', 'cast')()
  File "/home/kperkins/.virtualenvs/cast/local/lib/python2.7/site-packages/cast.py", line 73, in main
    cast = pychromecast.PyChromecast(CHROMECAST_HOST)
AttributeError: 'module' object has no attribute 'PyChromecast'
```

**Comment by jaapz** [comment]
Yeah, the pychromecast module has changed a lot since I built this little tool. I would like to update it but I don't think I'll find the time to do that in the near future. PR's are welcome though.
